spring:
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/university_db}

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

active-mq:
  teacher:
    topic: teacher.topic
  student:
    topic: student.topic